### ISSUE TITLE
Should this target HKCU, not HKLM?

### ISSUE THREAD

**Issue by aadennis** [PowerShell/xInternetExplorerHomePage#2]
The code references this Registry folder:
`$IEMainReg = 'HKLM:\Software\Microsoft\Internet Explorer\Main'`

While the referenced keys/values are correctly updated, perhaps you should target HKCU, not HKLM? Certainly that would mean the inclusion of [PsDscRunAsCredential] and therefore mandate the use of WMF 5.1, and required additional code to implement. But as DSC runs as System, I am struggling to understand the point of this cmdlet in its current form: if this is about IE defaults, then AFAIK using HKLM does not achieve this.

Thank you.

**Comment by johlju** [comment]
There seems to be registry entries there 

```
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Internet Explorer\Main]
"ApplicationTileImmersiveActivation"=dword:00000001
"AssociationActivationMode"=dword:00000000
"AutoHide"="yes"
"Start Page"="http://go.microsoft.com/fwlink/p/?LinkId=255141"
"Anchor_Visitation_Horizon"=hex:01,00,00,00
"Cache_Percent_of_Disk"=hex:0a,00,00,00
"Default_Page_URL"="http://go.microsoft.com/fwlink/p/?LinkId=255141"
"Default_Search_URL"="http://go.microsoft.com/fwlink/?LinkId=54896"
"Default_Secondary_Page_URL"=hex(7):00,00,00,00
"Delete_Temp_Files_On_Exit"="yes"
"Enable_Disk_Cache"="yes"
"Extensions Off Page"="about:NoAdd-ons"
"Local Page"="C:\\Windows\\System32\\blank.htm"
"Placeholder_Height"=hex:1a,00,00,00
"Placeholder_Width"=hex:1a,00,00,00
"Search Page"="http://go.microsoft.com/fwlink/?LinkId=54896"
"Security Risk Page"="about:SecurityRisk"
"Use_Async_DNS"="yes"
"x86AppPath"="C:\\Program Files (x86)\\Internet Explorer\\IEXPLORE.EXE"
```

So I think this resource is meant to be used to set the start page for new users?.

Your proposal would be allowed to set it for current users to, but that would only work for one user on the machine since two resources with the same key would fail.
